trigger: none

pool:
  vmImage: 'ubuntu-latest'

# variables:
#   location: 'eastus'
#   subscription_id: 'd8f91232-3cb0-4b1c-9a92-e0a39a04dbfa'
#   email_id: ['vkmallikarjun@gmail.com', 'civilstudents52@gmail.com']
#   buss: 'VK'
#   appname: 'GE'
#   env: 'DEV'
#   rg: 'NetworkWatcherRG'

steps:
# - script: |
#     # Authenticate with Azure
#     # az login --service-principal --username $(servicePrincipalId) --password $(servicePrincipalKey) --tenant $(tenantId)
#     # az account set --subscription $(subscriptionId)

- script: |
    terraform init 

- script: |
    cd monitor
    terraform plan var-file=auto.tfvars
 
#  - script: |
#     terraform apply -auto-approve 
#   displayName: 'Terraform Apply'
